image: Visual Studio 2017

version: 2.1.0.{build}

pull_requests:
  do_not_increment_build_number: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'

before_build:
- nuget restore

build:
  publish_nuget: true

deploy:
- provider: NuGet
  api_key:
    secure: lUmSV95QwsQtvPkHT02PT5fswmVcW0oMIJvOGEincUNnUNtTe3DOIjVEOpC0CMkQ
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master
